In [2]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

In [9]:
import kagglehub

# Download latest version
path = kagglehub.competition_download('m5-forecasting-accuracy')

print("Path to competition files:", path)

import os
for dirname, _, filenames in os.walk('/root/.cache/kagglehub/competitions/m5-forecasting-accuracy'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

Path to competition files: /root/.cache/kagglehub/competitions/m5-forecasting-accuracy
/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sample_submission.csv
/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sales_train_validation.csv
/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sales_train_evaluation.csv
/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/calendar.csv
/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sell_prices.csv

### 1. Load Dataset

In [10]:
import pandas as pd
calendar_df = pd.read_csv('/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/calendar.csv')
sell_prices_df = pd.read_csv('/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sell_prices.csv')
sales_train_evaluation_df = pd.read_csv('/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sales_train_evaluation.csv')
sales_train_validation_df = pd.read_csv('/root/.cache/kagglehub/competitions/m5-forecasting-accuracy/sales_train_validation.csv')

In [7]:
calendar_df.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [8]:
calendar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   object
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   object
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   object
 7   event_name_1  162 non-null    object
 8   event_type_1  162 non-null    object
 9   event_name_2  5 non-null      object
 10  event_type_2  5 non-null      object
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), object(7)
memory usage: 215.5+ KB

In [11]:
sell_prices_df.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [12]:
sell_prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    object
 1   item_id     object
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 208.8+ MB

In [15]:
sales_train_evaluation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1947 entries, id to d_1941
dtypes: int64(1941), object(6)
memory usage: 452.9+ MB

In [16]:
sales_train_validation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), object(6)
memory usage: 446.4+ MB